openapi: 3.0.1
info:
  title: FileUpload Example
  version: v1
paths:
  /WeatherForecast:
    post:
      tags:
        - WeatherForecast
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  nullable: true
            encoding:
              files:
                style: form
      responses:
        '200':
          description: Success
components: {}
